name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run Django migrations
        run: |
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_HOST=localhost \
          DB_PORT=5432 \
          SECRET_KEY=${{ secrets.SECRET_KEY }} \
          DEBUG=${{ secrets.DEBUG }} \
          EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} \
          EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }} \
          FT_OAUTH_CLIENT_ID=${{ secrets.FT_OAUTH_CLIENT_ID }} \
          FT_OAUTH_CLIENT_SECRET=${{ secrets.FT_OAUTH_CLIENT_SECRET }} \
          docker-compose run backend python manage.py migrate

      - name: Run Django tests
        run: |
          DB_NAME=${{ secrets.DB_NAME }} \
          DB_USER=${{ secrets.DB_USER }} \
          DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          DB_HOST=${{ secrets.DB_HOST }} \
          DB_PORT=5432 \
          SECRET_KEY=${{ secrets.SECRET_KEY }} \
          DEBUG=${{ secrets.DEBUG }} \
          EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} \
          EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }} \
          FT_OAUTH_CLIENT_ID=${{ secrets.FT_OAUTH_CLIENT_ID }} \
          FT_OAUTH_CLIENT_SECRET=${{ secrets.FT_OAUTH_CLIENT_SECRET }} \
          docker-compose run backend python manage.py test