name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:12
        env:
            POSTGRES_DB: 'inchoidb'
            POSTGRES_USER: 'inchoi'
            POSTGRES_PASSWORD: 'choi6240'
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U inchoi" 
          --health-interval 10s 
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
      
      - name: Run Django migrations
        run: |
          docker-compose run backend python manage.py migrate

      - name: Run Django tests
        run: |
          docker-compose run backend python manage.py test

      - name: Build and run frontend
        run: |
          docker-compose run frontend npm install
          docker-compose run frontend npm test